// UI reducer types
export const DATA_FETCH_COMPLETED = 'DATA_FETCH_COMPLETED';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const LOADING_UI = 'LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// User reducer types
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const UPLOAD_USER_IMAGE = 'UPLOAD_USER_IMAGE';
export const UPLOAD_COVER_IMAGE = 'UPLOAD_COVER_IMAGE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
// Tweet reducer types
export const SET_TWEETS = 'SET_TWEETS';
export const POST_TWEET = 'POST_TWEET';
export const UPDATE_TWEET = 'UPDATE_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const POST_RETWEET = 'POST_RETWEET';
export const DELETE_RETWEET = 'DELETE_RETWEET';
export const LIKE_TWEET = 'LIKE_TWEET';
export const UNLIKE_TWEET = 'UNLIKE_TWEET';
// Reply reducer types
export const SET_REPLIES = 'SET_REPLIES';
export const POST_REPLY = 'POST_REPLY';
export const UPDATE_REPLY = 'UPDATE_REPLY';
export const DELETE_REPLY = 'DELETE_REPLY';
export const LIKE_REPLY = 'LIKE_REPLY';
export const UNLIKE_REPLY = 'UNLIKE_REPLY';
// Signup reducer types
export const UPDATE_SIGNUP_FORM_DATA = 'UPDATE_SIGNUP_FORM_DATA';
export const SUBMIT_SIGNUP_FORM_DATA = 'SUBMIT_SIGNUP_FORM_DATA';
export const UPLOAD_CACHED_USER_IMAGE = 'UPLOAD_CACHED_USER_IMAGE';
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';
export const UPDATE_PASSWORD_STRENGTH = 'UPDATE_PASSWORD_STRENGTH';
export const SAVE_UNIQUE_IMAGE_ID = 'SAVE_UNIQUE_IMAGE_ID';
