// Data reducer types
export const CLEAR_STATE = 'CLEAR_STATE';
// UI reducer types
export const DATA_FETCH_COMPLETED = 'DATA_FETCH_COMPLETED';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const LOADING_UI = 'LOADING_UI';
export const LOADING_REPLIES = 'LOADING_REPLIES';
export const LOADING_USERS = 'LOADING_USERS';
export const USERS_FETCH_COMPLETED = 'USERS_FETCH_COMPLETED';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const PROFILE_TAB_CHANGE = 'PROFILE_TAB_CHANGE';
// User reducer types
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWING = 'SET_FOLLOWING';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const UPLOAD_USER_IMAGE = 'UPLOAD_USER_IMAGE';
export const UPLOAD_COVER_IMAGE = 'UPLOAD_COVER_IMAGE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
// Tweet reducer types
export const SET_TWEETS = 'SET_TWEETS';
export const POST_TWEET = 'POST_TWEET';
export const UPDATE_TWEET = 'UPDATE_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const POST_RETWEET = 'POST_RETWEET';
export const DELETE_RETWEET = 'DELETE_RETWEET';
export const LIKE_TWEET = 'LIKE_TWEET';
export const UNLIKE_TWEET = 'UNLIKE_TWEET';
export const SET_IS_BOOKMARK_TO_TWEETS = 'SET_IS_BOOKMARK_TO_TWEETS';
export const SET_IS_BOOKMARK = 'SET_IS_BOOKMARK';
// Reply reducer types
export const SET_REPLIES = 'SET_REPLIES';
export const POST_REPLY = 'POST_REPLY';
export const UPDATE_REPLY = 'UPDATE_REPLY';
export const DELETE_REPLY = 'DELETE_REPLY';
export const LIKE_REPLY = 'LIKE_REPLY';
export const UNLIKE_REPLY = 'UNLIKE_REPLY';
export const CLEAR_REPLIES = 'CLEAR_REPLIES';
// Signup reducer types
export const UPDATE_SIGNUP_FORM_DATA = 'UPDATE_SIGNUP_FORM_DATA';
export const SUBMIT_SIGNUP_FORM_DATA = 'SUBMIT_SIGNUP_FORM_DATA';
export const UPLOAD_CACHED_USER_IMAGE = 'UPLOAD_CACHED_USER_IMAGE';
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';
export const UPDATE_PASSWORD_STRENGTH = 'UPDATE_PASSWORD_STRENGTH';
export const SAVE_UNIQUE_IMAGE_ID = 'SAVE_UNIQUE_IMAGE_ID';
// Notifications reducer types
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const UPADTE_NOTIFICATIONS_READ = 'UPADTE_NOTIFICATIONS_READ';
// Bookmarks reducer types
export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const POST_BOOKMARK = 'POST_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
// Seach entry reducer types
export const POST_SEARCH_QUERY = 'POST_SEARCH_QUERY';
